version: '3'
services:
  web:
    hostname: web
    image: django_example_dev
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11